### ISSUE TITLE
[games] Mastermind 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#102]
"Här är en skiss på hur det skulle kunna se ut online. Och då har jag tänkt mig 
dubbel-mastermind.I vanligt mastermind gör ju kod-skaparen nästan ingeting 
förutom att placera ut feedback-pluppar. Men om man spelar dubbel-masternind 
kan man tävla mot varandra och då kan vi använda två hela sidor av huset. Jag 
tror det kan bli väldigt snyggt."

![playthehouse](https://cloud.githubusercontent.com/assets/6115389/4178389/8cb7a77c-3694-11e4-8b08-952a34a30771.jpg)

**Comment by FireyFly** [comment]
We now have a (very poor visually) implementation of two-player Mastermind (presently with hard-coded "hidden code").  The following is urgently needed:
- A separate "choose your code" step before the real game begins, where each player inputs what their hidden code is.
- User-interface updates:
  - The user interface needs to indicate whose each set of lamps are.
  - The user interface needs to indicate the "active" column to input a guess for.
  - The user interface needs to show "the colourpicker" after the first click (it's currently present all the time) and needs to indicate what lamp is being guessed.
  - It's currently hard to tell what reply belongs to which guess, which needs to be improved.
- The "reply" lamps need to support blinking--currently, they are red and blue for correct/almost correct.
- There needs to be more animations!
- More customization choices:
  - Currently, all colours are hard-coded
  - Orientation (game proceeds horizontally) is hard-coded
  - It'd be nice to allow both progression "from the outside in" and vice versa, i.e. start on the edges or start in the middle for the first guess.

Many of the UI-related issues have to do with the way our game code currently assumes that we want to render the game board as a rectangular grid of lamps, even though we might want to change things a bit for user-friendliness in this game.  This needs some work.

I think we should split this issue into smaller issues and distribute them, for instance one person could work on the frontend UI, one could work on the backend to add support for better game customization, and one could try to improve the way lightgames/simplegame works to accomodate "non-rectangular-grid" games (from a game frontend perspective, not a lamp-grid perspective).

**Comment by FireyFly** [comment]
This issue has been split up into sub-issues. This issue should be closed after all the sub-issues have been closed.
- #108: Mastermind: visual indication of where to click/whose turn it is games
- #109: Mastermind: rules text needs to be written games
- #110: Mastermind: code-definition phase games
- #111: Mastermind: support for configuration games
- #112: Mastermind: better response indicators

**Comment by FireyFly** [comment]
Closing this now as the Mastermind game has been rather fleshed out. More specific issues are more useful at this point.
