### ISSUE TITLE
After just starting the real light-server and then the webserver I get several ConnectionRefusedErrors. 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#11]

**Comment by ecryth** [comment]
When first starting the light server it will try to connect to the bridges listed in its configuration file. This will take a few seconds and the server won't start listening for requests until this is finished. In other words, this is likely a problem on the light server side. See smab/playhouse-lights#7 for an attempt to clarify this.

**Comment by wamanuz** [comment]
While that is a problem on the light server side, it is also a problem in the webserver. If it can't reach it  it should at least say something and maybe wait and retry after a second or two.
