### ISSUE TITLE
Mastermind: code-definition phase

### ISSUE THREAD

**Issue by FireyFly** [smab/playhouse-web#110]
A Mastermind game should consist of two phases. In the first phase, both players should define their secret code. The second phase is the actual game, where the players take guesses and get automatic responses in turn, and compete to be the first one to crack the opponents' code.

The second phase is implemented (although with hardcoded or random secret codes). The first phase as well as the "phase" infrastructure itself needs to be written.

**Comment by clid** [comment]
If a player hasn't defined the code in a certain time, a random code should probably just be assigned.

**Comment by FireyFly** [comment]
Implemented by Zetro a while ago.
