### ISSUE TITLE
Instead of a rullgardin, it should be some kind of area where one can select one entry

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#22]
Think Konversation channel selector. You can also group things, like gifanitmation, off and default, and games. 

@Zetro

**Comment by FireyFly** [comment]
Really, just a `<ul>` of links should work, I think. It could be styled to look a bit more fancy.

For grouping, the "special" games (that aren't quite games) could have a class property or maybe template variable to indicate that they are special, and be grouped above the other "proper" games. (That is, create two separate lists: one for "special" and one for regular games. The lists would be styled the same.)

**Comment by Zetro** [comment]
What would be the best way to get information about games?
I don't like the idea of executing each python-file in a folder to read some variable they define

**Comment by wamanuz** [comment]
Did not bother with groups.
