### ISSUE TITLE
[games] Memory's timeout thing yields bogus behaviour

### ISSUE THREAD

**Issue by FireyFly** [smab/playhouse-web#26]
For instance, when Alice presses two buttons of different colours and Bob then presses one of them while they remain lit, it'll become unlit even though it shouldn't be. This has severe effects if Bob then picks another same-colour tile.

**Comment by wamanuz** [comment]
Is this still a problem?

**Comment by wamanuz** [comment]
Flytta någon timeout från clientside till serverside

**Comment by tomaswic** [comment]
Put a sleep in the memory.py before the player is switched which seems to be working. You can still click the shown discs (the two non-matching that is shown by the opponents clicks) so that they become instantly filled when the turn is switched.

**Comment by clid** [comment]
The regular time.sleep blocks the entire webserver.
Made it non-blocking in https://github.com/smab/playhouse-web/commit/3d12f3a39267e2b5ca2277e6165e3b2a77263569
Had to add some logic too to not make new issues arise.
