### ISSUE TITLE
[games] Players should be informed if they are waiting for another player or if paired up initially

### ISSUE THREAD

**Issue by hleskela** [smab/playhouse-web#33]
When a player joins a game s/he should be informed whether s/he is currently paired up with someone or if s/he is all alone, just waiting for someone to show up.

**Comment by Zetro** [comment]
@wamanuz, will this issue be solved when #23 is done?
Faded out opponent (and perhaps some text) should make it clear if they are waiting or paired up.

**Comment by wamanuz** [comment]
Maybe this too should be with the new popup screen? Or is that too much?

**Comment by ecryth** [comment]
Remember not to focus too much on the specifics of how information is presented to the user, as the user-facing interface is not our priority. Focus on making sure that the information is sent from the web server in a straightforward way.

**Comment by clid** [comment]
Kind of fixed in https://github.com/smab/playhouse-web/commit/e5442576e10913c0737e008e6d1235870c694eb2

Maybe we should move the "You are player X" message into the sideboxes somehow, since they will only ever be seen by player 1 when there is no other player in the queue.
