### ISSUE TITLE
[config] Interface should only be reachable from a local network 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#34]

**Comment by webbmastern** [comment]
Fixed so that you need to be on local network to log in to [config] interface

**Comment by wamanuz** [comment]
That is so not a solution. It has to be made server side.

**Comment by wamanuz** [comment]
Then again, maybe restricting to local access is stupid? What if you want to configure it remotely?

**Comment by wamanuz** [comment]
Closed as it is a stupid idea. If you only want local access get a firewall to do it.
