### ISSUE TITLE
Mobile devices displays the queue in the middle of the page

### ISSUE THREAD

**Issue by hleskela** [smab/playhouse-web#36]
This is related to not letting the queuebox zoom in with the page with the position:absolute; property. This makes small screen devices display the page improperly when in landscape mode and when a big playfield is present. It can be fixed with a position:absolute tag in the body, but then the queuebox bugs for smaller playfields instead. Suggesting a better html structure, as I think this would be the easiest way.

**Comment by FireyFly** [comment]
This should certainly no longer be the case, now that the queue messagebar was first moved to above the play field, and then merged with the topbar. The positioning issue still remains, though, but #29 seems to be about this issue too.

**Comment by wamanuz** [comment]
We've decided this is not a problem after the bars have been merged and moved.
