### ISSUE TITLE
Rewrite diagnostics.py so that it can be executed from the config interface

### ISSUE THREAD

**Issue by migomipo** [smab/playhouse-web#39]
I wrote diagnostics.py (https://github.com/smab/playhouse-lights/blob/master/src/diagnostics.py) for checking how synchronized the lamps are when not using groups. This does have some uses, it can be used to check whether specific lamps are too slow, or to find bugs in the lamp server. 

This file could easily be rewritten as a web server 'game' for someone who understands the web server API. It would be convenient to be able to run this test from the config interface.

A more extensive test suite should also be implemented later, to test blink frequency, colours, colour "leaking" between windows, etc. etc.

**Comment by clid** [comment]
Done, https://github.com/smab/playhouse-web/commit/49cdd46edea8e76db9a6f371a1ba4fd324f49493

Not tested with lamps.
