### ISSUE TITLE
If playing paint and game changes, no information pops up.

### ISSUE THREAD

**Issue by webbmastern** [smab/playhouse-web#41]
If playing paint and game changes, no information pops up. It just stops working. The user will probably refresh webpage after a short moment.

**Comment by FireyFly** [comment]
Well, even "the game was destroyed" isn't exactly super user-friendly. But then again, the game isn't supposed to be changed frequently so I don't think it's much of an issue.

**Comment by webbmastern** [comment]
That's why it's labeled as an enhancement. But I can agree that it shouldn't be a high prio enhancement.

**Comment by wamanuz** [comment]
It's because there is no queue-bar. Add it (without the actual queue functionallity).

**Comment by wamanuz** [comment]
oops
