### ISSUE TITLE
[config] Make it clearer how the grid configuration works

### ISSUE THREAD

**Issue by ecryth** [smab/playhouse-web#58]
- What exactly happens when I click on a square? I can somewhat tell that the square gets associated with a lamp, but how do I know which lamp?
- When no bridges are added to the lamp server I get "No activated lamp" when trying to place a lamp. What does that mean?
- When I press "Test" I get "Unknown request", why and what does that mean?
- Why is the "Change Size" button sometimes disabled?
- What does "Refresh" do?

**Comment by wamanuz** [comment]
Things to put in the documentation!

**Comment by Zetro** [comment]
"Test" is diagnostics which is not implemented yet (#39)

**Comment by wamanuz** [comment]
You should probably rename the button.

**Comment by Zetro** [comment]
These points are now explained in the documentation

**Comment by wamanuz** [comment]
I think there should be some more explanation in the actual interface

**Comment by Zetro** [comment]
Then what exactly needs to be done?

**Comment by ecryth** [comment]
You could add descriptive text along the lines of "click the square belonging to the currently lit lamp" or whatever.

**Comment by Zetro** [comment]
Open a new issue if more needs to be done
