### ISSUE TITLE
[all] Document stuff 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#59]
@clid Queue and animations-api  
@FireyFly Game-api 
@wamanuz @Zetro Config-interface 

This is to be put in README.md. 
For example topics, see the protocol (2014-04-01)

**Comment by FireyFly** [comment]
Game API documentation has been added to the repository wiki: [Game API](https://github.com/smab/playhouse-web/wiki/Game%20API).

**Comment by clid** [comment]
Documentation about the Queue and GIF Animations has now been added to the wiki.

**Comment by Zetro** [comment]
Started on some documentation on configuration but not all that happy with it.
Anyone is free to do some major editing if they want.
Bridge config is currently undocumented and so is 'Preview' but that isn't even implemented yet.

**Comment by FireyFly** [comment]
What is the status on this issue? Should it be closed (because the most important documentation is done) or left open (as a reminder to continuously update the documentation, and because the documentation isn't completed yet so it arguably shouldn't be closed)?

**Comment by webbmastern** [comment]
To get a good overview I think that it should be closed and the parts that are not completed yet should get their own personal issue.
