### ISSUE TITLE
[config] Should be more persistent settings. 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#61]
I started it by making update_config save to file and moved the config_file variable to the manager, but I don't know where else important stuff is changed. 

I don't think current game (and its settings) needs be persistent, but most other stuff should. 

May also be a point to make the config.json more visually pleasing (e.g. if the user is expected to add a passwords/ssl/other stuff in it)

**Comment by Zetro** [comment]
Everything except game settings are persistent since 0dbb1b664a2543c9ee65273be9b523c5dcde2ee5.
Enough to close this?
