### ISSUE TITLE
[games] Rules button look butt ugly in chrome, and it should be moved 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#66]
It looks a little bit better in Firefox. 

List of places better than the current (below header): 
- Below the game board 
- Besides the join queue 
- Besides the header (e.g. Connect4 <rule button>). 

The popup should be moved below the game board. Perhaps it would work to anchorlink it to force scroll down there when pressed. 

Also, no rounded corners!

**Comment by tomaswic** [comment]
de-fancied the button and moved it below the board. Also added a autoscroll so when you click the button it focuses on the rules. Tested it in chromium and firefox.
