### ISSUE TITLE
[games] Increase the contrast 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#67]
It's a lot of dark colours on dark colours and I think it is difficult to read. 

It would be better if the background or to all text was whiter.

**Comment by FireyFly** [comment]
Commit [cb0b6910ce](https://github.com/smab/playhouse-web/commit/cb0b6910ce139282a3fb31917dc37dc049199fee) tries to fix this, but I'd like some comments before closing the issue. The old background colour was meant to be temporary anyway... actually, maybe some slight texture would be nice. Hm.

**Comment by webbmastern** [comment]
I think it looks really good. Perhaps it doesn't need to be perfect since some webdesigners will be working on it and probably change it for every installation.
