### ISSUE TITLE
[games] Weird stuff happens when new players join connect4 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#74]
Start a game and add two players to them. Play some moves and then leave. Add two new players and the hover-styling (and perhaps more) is wrong. 

Edit: Seems like win condition may be broken as well.

**Comment by wamanuz** [comment]
Heh, forgot that I already added this as #70

**Comment by FireyFly** [comment]
Reopening this rather than #70 as the wording here more accurately describes the problem. The problem is that the synchronization with clients weren't sent as "moves" but rather just as "lamp turn-on" commands (this distinction is necessary because of the drop-down animations). Pushing a fix...
