### ISSUE TITLE
Queue button behaves oddly

### ISSUE THREAD

**Issue by FireyFly** [smab/playhouse-web#75]
I noticed that the queue button seems to exhibit odd behaviour: pressing it as a spectator seems to (for some reason) cycle between receiving two messages `queuepos: 0` and `queuepos: 1`, or receiving `queuepos: 0` twice, or having the game sync its state to the client. I'm not sure what happens, but it doesn't seem to behave correctly. More investigation is needed.

I made some changes to the queue-button code when merging the queue bar with the general message area. I don't think those changes caused this, though.

**Comment by Zetro** [comment]
Probably line 42 in gamequeue.py that is causing this. Might be fixed by removing the session from sessions when leaving the queue (line 47 and line 75)
