### ISSUE TITLE
[games] Win/lose message needs to be clearer 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#85]
Move it from the message bar to the new popup for destroyed windows (which looks really good*) 
- Minor changes that should also be done: 
  - Change the message to something more descriptive, e.g. "Game changed, reloading..." and an automatic reload after a few secs. 
  - Increase the opacity of the text to make it clearer.

**Comment by clid** [comment]
Fixed in https://github.com/smab/playhouse-web/commit/13fceeba95c1720bed27efbf6f6d555cb3dee799
Win/lose messages now displays on the overlay.

Changed the destroy message to "Game changed, reloading...", and made it automatically reload.

Slightly increased the opacity of the text.
